### ISSUE TITLE
Set up wizard strips "q" from package name

### ISSUE THREAD

**Issue by colinvwood** [caporaso-lab/cookiecutter-qiime2-plugin#20]
Problem happens [here](https://github.com/caporaso-lab/cookiecutter-qiime2-plugin/blob/c7e7a98ac77291ba840dc4c5f5635b0a667588f2/cookiecutter.json#L4). The `removeprefix` method should probably be used instead. 

<img width="609" alt="Screenshot 2024-08-12 at 11 42 54 AM" src="https://github.com/user-attachments/assets/169a001e-63e3-4131-b16a-9bcea09761d8">

**Comment by gregcaporaso** [comment]
Oops, thanks @colinvwood!
